### ISSUE TITLE
empty XML after crawling on certain blogs

### ISSUE THREAD

**Issue by jonatanhal** [jonatanhal/blogg2forme#6]
testbloggar: 
+ elinjaconelli
+ lekindy

Enligt mina tester i commit https://github.com/jonatanhal/blogg2forme/commit/f0919f1102fa324801f71cd8ffc2fd9a8c5f529a så får jag ut en ordentlig xml, ska fortsätta testa & se

**Comment by jonatanhal** [comment]
Är problemet att skriptet inte startar iom. att det bara dyker upp `[DEBUG] Crawler.crawl - robotParser.can_fetch returned false` (isf öppnar jag upp ett nytt issue), eller körs skriptet men XML-filen är tom?

**Comment by sunkan** [comment]
Script funkar på min laptop. men dör när den parsar datum
