### ISSUE TITLE
Date parse

### ISSUE THREAD

**Issue by sunkan** [jonatanhal/blogg2forme#8]
Traceback (most recent call last):
  File "./main.py", line 88, in <module>
    status = main()
  File "./main.py", line 74, in main
    parser.Main()
  File "/home/sunkan/gir/blogg2forme/src/parser.py", line 1014, in Main
    self.assemblePost(url)
  File "/home/sunkan/gir/blogg2forme/src/parser.py", line 922, in assemblePost
    date = self.getDate(url)
  File "/home/sunkan/gir/blogg2forme/src/parser.py", line 502, in getDate
    return self.dateParse(date.text)
  File "/home/sunkan/gir/blogg2forme/src/parser.py", line 878, in dateParse
    year = int(self.yearRegex.search(string).group())
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jonatanhal** [comment]
Ska kolla upp det här, jag behöver dock veta vilken blogg du matat in i skriptet, tror det har att göra med vilket filter (eller vad man nu ska kalla det) som skriptet försöker tolka tiden genom.

**Comment by jonatanhal** [comment]
Jag håller på att göra om koden nu så att varje resultat från regex-matchningarna i `dateParse` först kollas om sökresultatet är None, vilket är problemet i det här fallet.

Om bloggen som skrapas använder ett tema som inte är standard, dvs ett tema från tredje part eller egenutvecklat tema för blogg.se (med datumformattering eller placering som *inte* följer de sätt som blogg.se organiserar timestamps i, t.ex. `"<div class="EttKonstigtClassNamnFörEnTimestamp">99, januari, 23 - Fredag. kl 15:22"</div>`) så kommer `dateParse` att faila. Detta eftersom `dateParse` inte matas med rätt (eller ibland ingen) info.

Det man skulle kunna göra för att underlätta sånna fall är att ifall dateParse failar, så sätts en sorts flagga i programmet som kan hanteras. T.ex. om datumet inte parsas ordentligt så görs ett email-utskick till bloggaren om att hen måste använda ett tema som programmet kan hantera (dvs. ett av de standard-teman som finns på blogg.se)

**Comment by jonatanhal** [comment]
Se commit https://github.com/jonatanhal/blogg2forme/commit/0904152896b08584eb968e0879db71de07fb37bf 

Felet som du träffade på,
```
File "/home/sunkan/gir/blogg2forme/src/parser.py", line 878, in dateParse
year = int(self.yearRegex.search(string).group())
AttributeError: 'NoneType' object has no attribute 'group'
```
kommer inte längre att uppstå, istället kommer ett `datetimeParserError`-exception att stoppa skriptet när skriptet körs mot en blogg som inte har ett utav blogg.se's standard-teman.
